name: Check Upstream and Trigger Build

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_upstream_release:
    runs-on: ubuntu-latest
    outputs:
      LATEST: ${{ steps.get_latest.outputs.LATEST }}
      
    steps:
      - name: Get LATEST upstream release
        id: get_latest
        run: |
          LATEST=$(curl -s https://api.github.com/repos/shinyflvre/Mate-Engine/releases/latest | jq -r '.tag_name')
          echo "LATEST=$LATEST" >> $GITHUB_OUTPUT
          
  trigger_build_update_tag:
    name: Trigger build and Update tag
    needs: check_upstream_release
    if: ${{ vars.STORED_ME_RELEASE != needs.check_upstream_release.outputs.LATEST }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update STORED_ME_RELEASE
        env:
           GITHUB_TOKEN: ${{ secrets.MEFORK_PHYSBONE_WRITE_VARS_TOKEN }}
           LATEST: ${{ needs.check_upstream_release.outputs.LATEST }}
        run: gh variable set STORED_ME_RELEASE --body "$LATEST"
          
      - name: Trigger Build Action
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: build_trigger