name: Check Upstream and Trigger Build

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_upstream_release:
    runs-on: ubuntu-latest

    steps:
      - name: Get LATEST upstream release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/shinyflvre/Mate-Engine/releases/latest | jq -r '.tag_name')
          echo "LATEST=$LATEST" >> $GITHUB_ENV
          
      - name: Trigger Build Action
        if: ${{ vars.LATEST_ME_RELEASE != env.LATEST }}
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: build_trigger